const JewelleryCardData = [
	{
		id: "1",
		images: Images.Jewellery1,
		title: "Gold Plated Necklace Set",
		description: "Traditional necklace with matching earrings.",
		price: "₹2999",
		oldPrice: "₹5999",
		discount: "50% Off",
		rating: 4.5,
		reviews: "12,540",
	},
	{
		id: "2",
		images: Images.Jewellery2,
		title: "Silver Oxidized Jhumkas",
		description: "Handcrafted oxidized earrings for ethnic wear.",
		price: "₹799",
		oldPrice: "₹1599",
		discount: "50% Off",
		rating: 4.2,
		reviews: "8,120",
	},
	{
		id: "3",
		images: Images.Jewellery3,
		title: "Diamond Engagement Ring",
		description: "Elegant solitaire ring with premium finish.",
		price: "₹49,999",
		oldPrice: "₹79,999",
		discount: "37% Off",
		rating: 4.8,
		reviews: "5,678",
	},
	{
		id: "4",
		images: Images.Jewellery4,
		title: "Pearl Bracelet",
		description: "Delicate pearl bracelet with adjustable chain.",
		price: "₹1499",
		oldPrice: "₹2799",
		discount: "46% Off",
		rating: 4.0,
		reviews: "7,245",
	},
	{
		id: "5",
		images: Images.Jewellery5,
		title: "Gold Bangles Set",
		description: "Set of 4 bangles with intricate design.",
		price: "₹5999",
		oldPrice: "₹9999",
		discount: "40% Off",
		rating: 4.7,
		reviews: "9,876",
	},
	{
		id: "6",
		images: Images.Jewellery6,
		title: "Kundan Choker Set",
		description: "Bridal choker set with royal Kundan work.",
		price: "₹6999",
		oldPrice: "₹12,999",
		discount: "46% Off",
		rating: 4.9,
		reviews: "15,420",
	},
];

const TrandingCardData = [
	{
		id: "1",
		images: Images.Teanding1,
		title: "Women Floral Printed Kurta",
		description: "Comfortable cotton kurta for daily wear.",
		price: "₹1499",
		oldPrice: "₹2499",
		discount: "40% Off",
		rating: 2.3,
		reviews: "12,345",
	},
	{
		id: "2",
		images: Images.Teanding2,
		title: "Men Slim Fit Casual Shirt",
		description: "Stylish and breathable fabric for summer.",
		price: "₹999",
		oldPrice: "₹1899",
		discount: "47% Off",
		rating: 4,
		reviews: "8,210",
	},
	{
		id: "3",
		images: Images.Teanding3,
		title: "Women Party Wear Gown",
		description: "Elegant evening gown with premium finish.",
		price: "₹2999",
		oldPrice: "₹4599",
		discount: "35% Off",
		rating: 4.6,
		reviews: "5,678",
	},
	{
		id: "4",
		images: Images.Teanding4,
		title: "Men Running Sports Shoes",
		description: "Lightweight shoes with durable sole.",
		price: "₹1799",
		oldPrice: "₹3299",
		discount: "45% Off",
		rating: 2.4,
		reviews: "15,420",
	},
	{
		id: "5",
		images: Images.Teanding5,
		title: "Women Handbag",
		description: "Trendy leather handbag with spacious design.",
		price: "₹1299",
		oldPrice: "₹2199",
		discount: "41% Off",
		rating: 5,
		reviews: "9,876",
	},
	{
		id: "6",
		images: Images.Teanding6,
		title: "Unisex Digital Smartwatch",
		description: "Track fitness & notifications on the go.",
		price: "₹2499",
		oldPrice: "₹4999",
		discount: "50% Off",
		rating: 1.5,
		reviews: "21,345",
	},
	{
		id: "7",
		images: Images.Teanding7,
		title: "Men Leather Wallet",
		description: "Premium quality wallet with multiple slots.",
		price: "₹799",
		oldPrice: "₹1499",
		discount: "47% Off",
		rating: 3.9,
		reviews: "6,543",
	},
	{
		id: "8",
		images: Images.Teanding8,
		title: "Wireless Bluetooth Earbuds",
		description: "Crystal clear sound with long battery life.",
		price: "₹1999",
		oldPrice: "₹3999",
		discount: "50% Off",
		rating: 4.8,
		reviews: "18,765",
	},
];
export default { JewelleryCardData, TrandingCardData };
